

name: Test Automation Workflow

on:
   schedule:
   - cron: 30 23 * * *
   push:
    branches: [ "master" ]
   pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running test automation framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true

    - name: Upload Test Reports
      if: always() 
      uses: actions/upload-artifact@v5.0.0
      with:
       name: Test logs
       path: logs/

    - name: Upload Test Reports
      if: always() 
      uses: actions/upload-artifact@v5.0.0
      with:
       name: Test Reports
       path: report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"
      
    
      

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
   
