name: Test Automation Workflow

on:
  schedule:
    - cron: '30 23 * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Run Test Automation Framework with Maven
        run: |
          while sleep 60; do echo "⌛ Tests are still running..."; done &
          timeout 20m mvn --batch-mode test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: test-logs
          path: logs/

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: test-report
          path: report.html

      - name: Test Execution Status
        run: echo "✅ Test Execution Completed"
